const matches = [
  {
    id: 1,
    date: "Domingo, 15 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 0,
        team2: 15,
        time: "02:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "Hard Rock (Miami)",
        score1: 0,
        score2: 0,
      },
      {
        id: 2,
        team1: 5,
        team2: 4,
        time: "18:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "TQL Stadium (Cincinnati)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 24,
        team2: 3,
        time: "21:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 2,
    date: "Lunes, 16 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 23,
        team2: 12,
        time: "00:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "MetLife Stadium (New York)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 9,
        team2: 28,
        time: "04:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 10,
        team2: 18,
        time: "21:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "Mercedes-Benz Stadium (Atlanta)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 3,
    date: "Martes, 17 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 7,
        team2: 6,
        time: "00:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "Hard Rock Stadium (Miami)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 13,
        team2: 11,
        time: "03:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 14,
        team2: 8,
        time: "18:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "MetLife Stadium (New York)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 27,
        team2: 30,
        time: "21:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 4,
    date: "Miercoles, 18 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 29,
        team2: 19,
        time: "00:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "Inter&Co Stadium (Orlando)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 21,
        team2: 16,
        time: "03:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 20,
        team2: 31,
        time: "18:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 25,
        team2: 2,
        time: "21:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "Hard Rock Stadium (Miami)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 5,
    date: "Jueves, 19 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 22,
        team2: 26,
        time: "00:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "TQL Stadium (Cincinnati)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 1,
        team2: 17,
        time: "03:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Audi Field (Washington D.C.)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 23,
        team2: 0,
        time: "18:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "MetLife Stadium (New York)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 15,
        team2: 12,
        time: "21:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "Mercedes-Benz Stadium (Atlanta)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 6,
    date: "Viernes, 20 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 28,
        team2: 3,
        time: "00:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 24,
        team2: 9,
        time: "03:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 6,
        team2: 4,
        time: "18:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "Inter&Co Stadium (Orlando)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 13,
        team2: 10,
        time: "20:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 7,
    date: "Sabado, 21 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 18,
        team2: 11,
        time: "00:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "GEODIS Park (Nashville)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 5,
        team2: 7,
        time: "03:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "Hard Rock Stadium (Miami)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 19,
        team2: 8,
        time: "18:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "TQL Stadium (Cincinnati)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 16,
        team2: 30,
        time: "21:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 8,
    date: "Domingo, 22 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 14,
        team2: 29,
        time: "00:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "MetLife Stadium (New York)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 27,
        team2: 21,
        time: "03:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 17,
        team2: 31,
        time: "18:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 25,
        team2: 22,
        time: "21:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "Bank of America Stadium (Charlotte)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 9,
    date: "Monday, 23 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 26,
        team2: 2,
        time: "00:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "Audi Field (Washington D.C.)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 20,
        team2: 1,
        time: "03:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Mercedes-Benz Stadium (Atlanta)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 28,
        team2: 24,
        time: "21:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 3,
        team2: 9,
        time: "21:00",
        stage: "Group stage",
        group: "Group B",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 10,
    date: "Martes, 24 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 15,
        team2: 23,
        time: "03:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "Hard Rock Stadium (Miami)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 12,
        team2: 0,
        time: "03:00",
        stage: "Group stage",
        group: "Group A",
        stadium: "MetLife Stadium (New York)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 4,
        team2: 7,
        time: "21:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "GEODIS Park (Nashville)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 6,
        team2: 5,
        time: "21:00",
        stage: "Group stage",
        group: "Group C",
        stadium: "Bank of America Stadium (Charlotte)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 11,
    date: "Miercoles, 25 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 18,
        team2: 13,
        time: "03:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "Camping World Stadium (Orlando)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 11,
        team2: 10,
        time: "03:00",
        stage: "Group stage",
        group: "Group D",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 8,
        team2: 29,
        time: "21:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "TQL Stadium (Cincinnati)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 19,
        team2: 14,
        time: "21:00",
        stage: "Group stage",
        group: "Group F",
        stadium: "Hard Rock Stadium (Miami)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 12,
    date: "Jueves, 26 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 16,
        team2: 27,
        time: "03:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Lumen Field (Seattle)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 30,
        team2: 21,
        time: "03:00",
        stage: "Group stage",
        group: "Group E",
        stadium: "Rose Bowl (Los Angeles)",
        score1: -1,
        score2: -1,
      },
      {
        id: 3,
        team1: 17,
        team2: 20,
        time: "21:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Camping World Stadium (Orlando)",
        score1: -1,
        score2: -1,
      },
      {
        id: 4,
        team1: 31,
        team2: 1,
        time: "21:00",
        stage: "Group stage",
        group: "Group G",
        stadium: "Audi Field (Washington D.C.)",
        score1: -1,
        score2: -1,
      },
    ],
  },
  {
    id: 13,
    date: "Viernes, 27 de Junio, 2025",
    matches: [
      {
        id: 1,
        team1: 2,
        team2: 22,
        time: "03:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "GEODIS Park (Nashville)",
        score1: -1,
        score2: -1,
      },
      {
        id: 2,
        team1: 26,
        team2: 25,
        time: "03:00",
        stage: "Group stage",
        group: "Group H",
        stadium: "Lincoln Financial Field (Philadelphia)",
        score1: -1,
        score2: -1,
      },
    ],
  },
];

module.exports = matches;
